QGIS: fix color ramp
storm-fsv-cvut/smoderp2d pull request #246
Opened 2023-10-11 18:59 UTC by landam

Fix #230

2023-10-11 19:01 UTC, landam commented
Issue to be solved: wrong legend

![image](https://github.com/storm-fsv-cvut/smoderp2d/assets/5683186/6bf6fb2a-2d33-496c-94e4-111907097054)

Open symbology dialog, click OK:

![image](https://github.com/storm-fsv-cvut/smoderp2d/assets/5683186/6adefd14-381b-4221-9152-db4cf00641ca)

2023-10-11 19:23 UTC, landam commented
See https://gis.stackexchange.com/questions/420407/pyqgis-legend-doesnt-update-with-renderer

2023-10-13 09:24 UTC, landam commented
Tested on Linux (Debian) and MS Windows. Seems to be fixed.

![VirtualBox_MS Windows_13_10_2023_11_23_49](https://github.com/storm-fsv-cvut/smoderp2d/assets/5683186/9d36e2ca-2fd1-4c98-b243-b2ae4375dadc)

2023-10-13 12:37 UTC, pesekon2 requested changes

2023-10-13 12:37 UTC, pesekon2 commented on smoderp2d/__init__.py
> +        color_ramp = QgsGradientColorRamp(QColor(239, 239, 255), QColor(  0,   0, 255))
```suggestion
        color_ramp = QgsGradientColorRamp(QColor(239, 239, 255), QColor(0,   0, 255))
```

2023-10-13 12:37 UTC, pesekon2 commented on smoderp2d/__init__.py
> +        )
```suggestion
        from qgis.core import QgsProject, QgsRasterLayer
```

2023-10-13 12:38 UTC, pesekon2 commented
Works also at my machine:

![image](https://github.com/storm-fsv-cvut/smoderp2d/assets/17025405/58226539-5624-46a5-8e8f-07ce47617723)

@landam Please, see two small change requests above and merge.

2023-10-13 19:04 UTC, pesekon2 approved these changes

2023-10-13 20:57 UTC, merged